### ISSUE TITLE
Independent (non-fork) repo

### ISSUE THREAD

**Issue by johnweldon** [go-asn1-ber/asn1-ber#14]
@liggitt How did we get the go-ldap repo marked as an independent (non-fork) repo?

I'd like to initiate that process with this repo too if possible, and if that seems right.

**Comment by liggitt** [comment]
You'd need to contact github support and ask them to detach this repo from the zerklabs/asn1-ber fork network (but leave downstream forks intact)

**Comment by johnweldon** [comment]
Thanks @nickcannariato
