### ISSUE TITLE
Go 1.10 incompatability

### ISSUE THREAD

**Issue by gaffo** [go-asn1-ber/asn1-ber#20]
gopkg.in/asn1-ber.v1/ber_test.go:19: Error call has possible formatting directive %d

**Comment by johnweldon** [comment]
This is fixed in master; just hasn't been in a tagged release yet.

**Comment by gaffo** [comment]
it'd be great if you could tag and release it

**Comment by johnweldon** [comment]
Let's get PR's #17, #18, and #19 merged and then we'll tag it

**Comment by vetinari** [comment]
merged those 3 w/ current master, sorry for the late action, didn't see it was still open

**Comment by johnweldon** [comment]
Tagged and released `v1.5.0`
