### ISSUE TITLE
Go module support not working

### ISSUE THREAD

**Issue by sunkica** [go-asn1-ber/asn1-ber#23]
One of the modules in my project requires this library, but when I try importing it, the process fails.

```
go test
go: finding gopkg.in/asn1-ber.v1 v1.3.1
build test/project: cannot load gopkg.in/asn1-ber.v1: cannot find module providing package gopkg.in/asn1-ber.v1
```

If I try to get it manually, the version validation fails.
```
go get gopkg.in/asn1-ber.v1
go: finding gopkg.in/asn1-ber.v1 v1.3.1
go get gopkg.in/asn1-ber.v1: gopkg.in/asn1-ber.v1@v1.3.1: invalid version: go.mod has non-....v1 module path "github.com/go-asn1-ber/asn1-ber" at revision v1.3.1
```

**Comment by sunkica** [comment]
Looks like this is an issue with the gopkg.in import in the module I'm importing. If I add a replace statement to the go.mod file that points to the github.com module, it seems to work fine.

`replace gopkg.in/asn1-ber.v1 => github.com/go-asn1-ber/asn1-ber v1.3.1`

**Comment by tsureshkumar** [comment]
I think the go.mod file in v1.3.1 tag of this repo ideally should have 

```golang
module "gopkg.in/asn1-ber.v1"
```

to work as gopkg.in module instead of

```golang
module github.com/go-asn1-ber/asn1-ber
```

Should that be submitted as patch, bumping the version?

**Comment by harrisonhjones** [comment]
Any thoughts on this? I ran into this issue today. I was able to get it to work following @sunkica's `replace` operation but it would be nice to fix it properly.

**Comment by johnweldon** [comment]
The go-ldap library has migrated to using github.com/go-asn1-ber/asn1-ber instead of gopkg.in: https://github.com/go-ldap/ldap/blob/master/go.mod

I would say that importing from github is the preferred approach now.

**Comment by josephglaspie** [comment]
Thanks for the update @johnweldon

Changing 
`import "gopkg.in/ldap.v2"` 
to
`import "ldap github.com/go-ldap/ldap/v3"`

did the trick!
