### ISSUE TITLE
TestParseGeneralizedTime fails on 32bit architectures

### ISSUE THREAD

**Issue by decathorpe** [go-asn1-ber/asn1-ber#29]
I'm the maintainer of the fedora package of this go library, and with version 1.5.0 I get this output from `go test` on i686 and armv7hl architectures:

```
      testing: gopkg.in/asn1-ber.v1
gopkg.in/asn1-ber.v1
--- FAIL: TestParseGeneralizedTime (0.00s)
    generalizedTime_test.go:81: test got unexpected result: wanted=2017-02-22 19:15:00 +0000 UTC, got=2017-02-22 18:59:57.852516352 +0000 UTC
    generalizedTime_test.go:81: test got unexpected result: wanted=2017-02-22 19:05:15 +0000 UTC, got=2017-02-22 19:04:57.852516352 +0000 UTC
FAIL
```

This looks like a loss of precision on 32bit architectures?
I'm not sure if this is a problem in the date parsing code itself or in this specific test.

**Comment by johnweldon** [comment]
Thanks @decathorpe

**Comment by decathorpe** [comment]
Thanks! That was fast :rocket:
