### ISSUE TITLE
ReadPacket returns UnexpectedEOF instead of EOF

### ISSUE THREAD

**Issue by LeGEC** [go-asn1-ber/asn1-ber#34]
`ReadPacket(reader io.Reader)` returns `io.ErrUnexpectedEOF`, when called on a reader which has reached EOF.

This makes it hard to distinguish between truncated data (an actual error), and a plain EOF, which can occur when reading a stream of ASN.1 packets (for example : reading successive ASN.1 packets from a connection to an LDAP server).

I would suggest to not turn `io.EOF` to `io.ErrUnexpectedEOF` when it occurs on reading the very first byte of the would be ASN.1 packet.

### Steps to reproduce :

run :

```
// call ReadPacket on an empty buffer :
_, err := ReadPacket(bytes.NewReader(nil))
fmt.Println(err)
```

expected :

```
EOF
```

actual :

```
unexpected EOF
```

**Comment by wfernandes** [comment]
@johnweldon Were you able to verify this issue? I notice this error when using `ldapsearch` as a client to our ldap server implementation that does `ber.ReadPacket()`.
It would be great to get @LeGEC's PR merged in if possible.
Thanks.

**Comment by johnweldon** [comment]
I've fallen dreadfully behind in managing this project.  I'd like to find some help maintaining it, but in the meanwhile I'll try to find some time to review all the outstanding issues and PR's.

Sorry for the delay!

**Comment by LeGEC** [comment]
Hello
Any news ?
