### ISSUE TITLE
Update license?

### ISSUE THREAD

**Issue by liggitt** [go-asn1-ber/asn1-ber#4]
Not sure why the license lists the go authors as the copyright holder...

might be painful to update, since the license is inherited from the original repo, but it doesn't appear like there was much discussion around it (went in with https://github.com/mmitton/asn1-ber/pull/8)

**Comment by johnweldon** [comment]
I'm not sure what the legal steps are to re-license.  My preference would be an MIT license, but I think you have to have agreement from the original license holders to change it.  Maybe the original licensing was just ad-hoc by @mmitton ?

**Comment by mmitton** [comment]
Original license changed to MIT.  Feel free to update your repo.

**Comment by johnweldon** [comment]
Thank you @mmitton !

**Comment by johnweldon** [comment]
@liggitt interesting reading [here](http://zguide.zeromq.org/page:all#The-Importance-of-Contracts).

I haven't thought about licensing enough to really debate the point, but that link seems compelling.  I've always preferred MIT for its simplicity and openness.

**Comment by psywolf** [comment]
I'd be particularly happy to see this change go through.  I'd like to use this and contribute to this at work. It'll be much easier to get approved with a more well known permissive licence such as MIT.
