### ISSUE TITLE
Support for the choice structure

### ISSUE THREAD

**Issue by Denis-shl** [go-asn1-ber/asn1-ber#44]
Hi, I'm trying to implement on go getting a keytab in an IPA. The documentation says that I need to implement an extended operation and encrypt the data for it using asn1. Can you tell me with the help of this library is it possible to do this?

https://www.freeipa.org/page/V4/Keytab_Retrieval#new-extended-operation

**Comment by cpuschma** [comment]
This is the wrong repository, but see https://github.com/go-ldap/ldap/pull/516 as I'm already trying to implement the extended operation into the go-ldap library. I haven't got the time to finish it of but you're free to review the code, test it and give some feedback :)
